// Mock post data for demo
import { mockUsers } from "./users.js";

export const mockPosts = [
  {
    _id: "post1",
    author: mockUsers[0],
    content: { text: "Just watched the GTA 6 trailer for the 100th time! Can't wait for November 2026! 🎮🔥" },
    media: [],
    engagement: {
      likes: 234,
      reposts: 45,
      comments: 12,
      bookmarks: 67,
      views: 1200,
      quotes: 0,
    },
    likes: 234,
    reposts: 45,
    comments: 12,
    bookmarks: 67,
    views: 1200,
    isLiked: false,
    isReposted: false,
    isBookmarked: false,
    type: "post",
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000), // 2 hours ago
    isEdited: false,
    isEditable: true,
  },
  {
    _id: "post2",
    author: mockUsers[1],
    content: { text: "Team Lucia! She's going to be such an amazing character. The character development looks incredible! 💪" },
    media: [
      {
        type: "image",
        url: "/images/HeaderImages/LuciaPool.jpg",
        thumbnail: "/images/HeaderImages/LuciaPool.jpg",
      },
    ],
    engagement: {
      likes: 567,
      reposts: 89,
      comments: 34,
      bookmarks: 123,
      views: 3400,
      quotes: 0,
    },
    likes: 567,
    reposts: 89,
    comments: 34,
    bookmarks: 123,
    views: 3400,
    isLiked: true,
    isReposted: false,
    isBookmarked: false,
    type: "post",
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000), // 5 hours ago
    isEdited: false,
    isEditable: true,
  },
  {
    _id: "post3",
    author: mockUsers[2],
    content: { text: "Jason's backstory is going to be wild. Can't wait to see how his story unfolds in Vice City!" },
    media: [],
    engagement: {
      likes: 189,
      reposts: 23,
      comments: 8,
      bookmarks: 45,
      views: 890,
      quotes: 0,
    },
    likes: 189,
    reposts: 23,
    comments: 8,
    bookmarks: 45,
    views: 890,
    isLiked: false,
    isReposted: true,
    isBookmarked: false,
    type: "repost",
    originalPost: {
      _id: "post3_original",
      author: mockUsers[3],
      content: { text: "New Jason character details revealed!" },
      engagement: {
        likes: 500,
        reposts: 100,
        comments: 50,
        bookmarks: 75,
        views: 2000,
        quotes: 0,
      },
      createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000),
    },
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000), // 3 hours ago
    isEdited: false,
    isEditable: true,
  },
  {
    _id: "post4",
    author: mockUsers[3],
    content: { text: "Breaking: New GTA 6 gameplay footage leaked! Check out the incredible graphics and physics engine. This is going to be a game-changer! 🚀" },
    media: [
      {
        type: "image",
        url: "/images/HeaderImages/draco.jpg",
        thumbnail: "/images/HeaderImages/draco.jpg",
      },
      {
        type: "image",
        url: "/images/HeaderImages/RaulBoat.jpg",
        thumbnail: "/images/HeaderImages/RaulBoat.jpg",
      },
    ],
    engagement: {
      likes: 1234,
      reposts: 456,
      comments: 89,
      bookmarks: 234,
      views: 8900,
      quotes: 0,
    },
    likes: 1234,
    reposts: 456,
    comments: 89,
    bookmarks: 234,
    views: 8900,
    isLiked: true,
    isReposted: false,
    isBookmarked: true,
    type: "post",
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000), // 1 day ago
    isEdited: false,
    isEditable: true,
  },
  {
    _id: "post5",
    author: mockUsers[4],
    content: { text: "Vice City at sunset is going to be absolutely stunning! The attention to detail in the environment is mind-blowing. 🌅" },
    media: [
      {
        type: "image",
        url: "/images/HeaderImages/Stripaz.jpg",
        thumbnail: "/images/HeaderImages/Stripaz.jpg",
      },
    ],
    engagement: {
      likes: 345,
      reposts: 67,
      comments: 23,
      bookmarks: 89,
      views: 2100,
      quotes: 0,
    },
    likes: 345,
    reposts: 67,
    comments: 23,
    bookmarks: 89,
    views: 2100,
    isLiked: false,
    isReposted: false,
    isBookmarked: false,
    type: "post",
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000), // 4 hours ago
    isEdited: false,
    isEditable: true,
  },
  {
    _id: "post6",
    author: mockUsers[0],
    content: { text: "The map size is going to be massive! Can't wait to explore every corner of Vice City and beyond! 🗺️" },
    media: [],
    engagement: {
      likes: 678,
      reposts: 123,
      comments: 45,
      bookmarks: 156,
      views: 4500,
      quotes: 0,
    },
    likes: 678,
    reposts: 123,
    comments: 45,
    bookmarks: 156,
    views: 4500,
    isLiked: true,
    isReposted: false,
    isBookmarked: false,
    type: "post",
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000), // 6 hours ago
    isEdited: true,
    isEditable: true,
  },
  // Multi-image post (3 images)
  {
    _id: "post7",
    author: mockUsers[1],
    content: { text: "Vice City vibes are unmatched! Here's a collection of my favorite screenshots from the trailer. Which one is your favorite? 📸✨" },
    media: [
      {
        type: "image",
        url: "/images/HeaderImages/LuciaPool.jpg",
        thumbnail: "/images/HeaderImages/LuciaPool.jpg",
      },
      {
        type: "image",
        url: "/images/HeaderImages/Bros.jpg",
        thumbnail: "/images/HeaderImages/Bros.jpg",
      },
      {
        type: "image",
        url: "/images/HeaderImages/Stripaz.jpg",
        thumbnail: "/images/HeaderImages/Stripaz.jpg",
      },
    ],
    engagement: {
      likes: 892,
      reposts: 156,
      comments: 78,
      bookmarks: 234,
      views: 5600,
      quotes: 12,
    },
    likes: 892,
    reposts: 156,
    comments: 78,
    bookmarks: 234,
    views: 5600,
    isLiked: false,
    isReposted: false,
    isBookmarked: true,
    type: "post",
    createdAt: new Date(Date.now() - 7 * 60 * 60 * 1000), // 7 hours ago
    isEdited: false,
    isEditable: true,
  },
  // Multi-image post (4 images)
  {
    _id: "post8",
    author: mockUsers[3],
    content: { text: "Breaking down the key locations we've seen so far in GTA 6. The attention to detail is incredible! 🏙️" },
    media: [
      {
        type: "image",
        url: "/images/HeaderImages/draco.jpg",
        thumbnail: "/images/HeaderImages/draco.jpg",
      },
      {
        type: "image",
        url: "/images/HeaderImages/RaulBoat.jpg",
        thumbnail: "/images/HeaderImages/RaulBoat.jpg",
      },
      {
        type: "image",
        url: "/images/HeaderImages/Bros.jpg",
        thumbnail: "/images/HeaderImages/Bros.jpg",
      },
      {
        type: "image",
        url: "/images/HeaderImages/BikerGang.jpg",
        thumbnail: "/images/HeaderImages/BikerGang.jpg",
      },
    ],
    engagement: {
      likes: 2345,
      reposts: 678,
      comments: 234,
      bookmarks: 567,
      views: 12300,
      quotes: 45,
    },
    likes: 2345,
    reposts: 678,
    comments: 234,
    bookmarks: 567,
    views: 12300,
    isLiked: true,
    isReposted: false,
    isBookmarked: true,
    type: "post",
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000), // 8 hours ago
    isEdited: false,
    isEditable: true,
  },
  // Video post
  {
    _id: "post9",
    author: mockUsers[2],
    content: { text: "Check out this amazing gameplay analysis! The physics and graphics are next level. Can't wait to experience this myself! 🎮🔥" },
    media: [
      {
        type: "video",
        url: "/src/assets/mockuser_videos/GTA6Trailer1_OG.mp4",
        thumbnail: "/images/HeaderImages/draco.jpg",
        metadata: {
          duration: 45,
          dimensions: { width: 1920, height: 1080 },
        },
      },
    ],
    engagement: {
      likes: 1456,
      reposts: 345,
      comments: 123,
      bookmarks: 456,
      views: 8900,
      quotes: 23,
    },
    likes: 1456,
    reposts: 345,
    comments: 123,
    bookmarks: 456,
    views: 8900,
    isLiked: true,
    isReposted: false,
    isBookmarked: false,
    type: "post",
    createdAt: new Date(Date.now() - 9 * 60 * 60 * 1000), // 9 hours ago
    isEdited: false,
    isEditable: true,
  },
  // Quote post
  {
    _id: "post10",
    author: mockUsers[4],
    content: { text: "This is exactly what I've been saying! The character development is going to be incredible. Can't wait to see more! 💯" },
    media: [],
    engagement: {
      likes: 234,
      reposts: 45,
      comments: 12,
      bookmarks: 67,
      views: 1200,
      quotes: 0,
    },
    likes: 234,
    reposts: 45,
    comments: 12,
    bookmarks: 67,
    views: 1200,
    isLiked: false,
    isReposted: false,
    isBookmarked: false,
    type: "quote",
    originalPost: {
      _id: "post10_original",
      author: mockUsers[1],
      content: { text: "Team Lucia! She's going to be such an amazing character. The character development looks incredible! 💪" },
      media: [
        {
          type: "image",
          url: "/images/HeaderImages/LuciaPool.jpg",
          thumbnail: "/images/HeaderImages/LuciaPool.jpg",
        },
      ],
      engagement: {
        likes: 567,
        reposts: 89,
        comments: 34,
        bookmarks: 123,
        views: 3400,
        quotes: 0,
      },
      createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000),
    },
    createdAt: new Date(Date.now() - 10 * 60 * 60 * 1000), // 10 hours ago
    isEdited: false,
    isEditable: true,
  },
  // Quote post with video
  {
    _id: "post11",
    author: mockUsers[0],
    content: { text: "This analysis is spot on! The attention to detail in the environment is mind-blowing. Rockstar never disappoints! 🎯" },
    media: [],
    engagement: {
      likes: 567,
      reposts: 123,
      comments: 45,
      bookmarks: 156,
      views: 3400,
      quotes: 0,
    },
    likes: 567,
    reposts: 123,
    comments: 45,
    bookmarks: 156,
    views: 3400,
    isLiked: true,
    isReposted: false,
    isBookmarked: false,
    type: "quote",
    originalPost: {
      _id: "post11_original",
      author: mockUsers[2],
      content: { text: "Check out this amazing gameplay analysis! The physics and graphics are next level. Can't wait to experience this myself! 🎮🔥" },
      media: [
        {
          type: "video",
          url: "/src/assets/mockuser_videos/gta6Trailer2_OG.mp4",
          thumbnail: "/images/HeaderImages/draco.jpg",
          metadata: {
            duration: 45,
            dimensions: { width: 1920, height: 1080 },
          },
        },
      ],
      engagement: {
        likes: 1456,
        reposts: 345,
        comments: 123,
        bookmarks: 456,
        views: 8900,
        quotes: 0,
      },
      createdAt: new Date(Date.now() - 9 * 60 * 60 * 1000),
    },
    createdAt: new Date(Date.now() - 11 * 60 * 60 * 1000), // 11 hours ago
    isEdited: false,
    isEditable: true,
  },
  // Repost with multi-image original
  {
    _id: "post12",
    author: mockUsers[1],
    content: { text: "" },
    media: [],
    engagement: {
      likes: 0,
      reposts: 0,
      comments: 0,
      bookmarks: 0,
      views: 0,
      quotes: 0,
    },
    likes: 0,
    reposts: 0,
    comments: 0,
    bookmarks: 0,
    views: 0,
    isLiked: false,
    isReposted: true,
    isBookmarked: false,
    type: "repost",
    originalPost: {
      _id: "post8",
      author: mockUsers[3],
      content: { text: "Breaking down the key locations we've seen so far in GTA 6. The attention to detail is incredible! 🏙️" },
      media: [
        {
          type: "image",
          url: "/images/HeaderImages/draco.jpg",
          thumbnail: "/images/HeaderImages/draco.jpg",
        },
        {
          type: "image",
          url: "/images/HeaderImages/RaulBoat.jpg",
          thumbnail: "/images/HeaderImages/RaulBoat.jpg",
        },
        {
          type: "image",
          url: "/images/HeaderImages/Bros.jpg",
          thumbnail: "/images/HeaderImages/Bros.jpg",
        },
        {
          type: "image",
          url: "/images/HeaderImages/BikerGang.jpg",
          thumbnail: "/images/HeaderImages/BikerGang.jpg",
        },
      ],
      engagement: {
        likes: 2345,
        reposts: 678,
        comments: 234,
        bookmarks: 567,
        views: 12300,
        quotes: 45,
      },
      createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000),
    },
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000), // 12 hours ago
    isEdited: false,
    isEditable: true,
  },
  // Text-only post with high engagement
  {
    _id: "post13",
    author: mockUsers[3],
    content: { text: "The wait is almost over! Just a few more years until we can finally explore Vice City in all its glory. Who else is counting down the days? ⏰🎮" },
    media: [],
    engagement: {
      likes: 3456,
      reposts: 890,
      comments: 456,
      bookmarks: 1234,
      views: 15600,
      quotes: 78,
    },
    likes: 3456,
    reposts: 890,
    comments: 456,
    bookmarks: 1234,
    views: 15600,
    isLiked: true,
    isReposted: true,
    isBookmarked: true,
    type: "post",
    createdAt: new Date(Date.now() - 13 * 60 * 60 * 1000), // 13 hours ago
    isEdited: false,
    isEditable: true,
  },
  // Single image post
  {
    _id: "post14",
    author: mockUsers[4],
    content: { text: "The neon lights of Vice City are going to be absolutely stunning at night! 🌃✨" },
    media: [
      {
        type: "image",
        url: "/images/HeaderImages/Stripaz.jpg",
        thumbnail: "/images/HeaderImages/Stripaz.jpg",
      },
    ],
    engagement: {
      likes: 456,
      reposts: 89,
      comments: 34,
      bookmarks: 123,
      views: 2800,
      quotes: 5,
    },
    likes: 456,
    reposts: 89,
    comments: 34,
    bookmarks: 123,
    views: 2800,
    isLiked: false,
    isReposted: false,
    isBookmarked: false,
    type: "post",
    createdAt: new Date(Date.now() - 14 * 60 * 60 * 1000), // 14 hours ago
    isEdited: false,
    isEditable: true,
  },
  // Multi-image post (2 images)
  {
    _id: "post15",
    author: mockUsers[0],
    content: { text: "Side by side comparison of the old and new Vice City. The evolution is incredible! 📊" },
    media: [
      {
        type: "image",
        url: "/images/HeaderImages/Bros.jpg",
        thumbnail: "/images/HeaderImages/Bros.jpg",
      },
      {
        type: "image",
        url: "/images/HeaderImages/RaulBoat.jpg",
        thumbnail: "/images/HeaderImages/RaulBoat.jpg",
      },
    ],
    engagement: {
      likes: 1234,
      reposts: 345,
      comments: 156,
      bookmarks: 456,
      views: 6700,
      quotes: 23,
    },
    likes: 1234,
    reposts: 345,
    comments: 156,
    bookmarks: 456,
    views: 6700,
    isLiked: true,
    isReposted: false,
    isBookmarked: true,
    type: "post",
    createdAt: new Date(Date.now() - 15 * 60 * 60 * 1000), // 15 hours ago
    isEdited: false,
    isEditable: true,
  },
  // Video post with text
  {
    _id: "post16",
    author: mockUsers[1],
    content: { text: "The character animations are so smooth! This is going to be the most immersive GTA experience yet! 🎬" },
    media: [
      {
        type: "video",
        url: "/src/assets/mockuser_videos/GTA6trailer1_Edited.mp4",
        thumbnail: "/images/HeaderImages/LuciaPool.jpg",
        metadata: {
          duration: 30,
          dimensions: { width: 1920, height: 1080 },
        },
      },
    ],
    engagement: {
      likes: 2345,
      reposts: 567,
      comments: 234,
      bookmarks: 678,
      views: 11200,
      quotes: 45,
    },
    likes: 2345,
    reposts: 567,
    comments: 234,
    bookmarks: 678,
    views: 11200,
    isLiked: true,
    isReposted: false,
    isBookmarked: true,
    type: "post",
    createdAt: new Date(Date.now() - 16 * 60 * 60 * 1000), // 16 hours ago
    isEdited: false,
    isEditable: true,
  },
  // Quote post with multi-image original
  {
    _id: "post17",
    author: mockUsers[2],
    content: { text: "Couldn't agree more! These locations are going to be amazing to explore. The detail is insane! 🔥" },
    media: [],
    engagement: {
      likes: 345,
      reposts: 78,
      comments: 23,
      bookmarks: 89,
      views: 2100,
      quotes: 0,
    },
    likes: 345,
    reposts: 78,
    comments: 23,
    bookmarks: 89,
    views: 2100,
    isLiked: false,
    isReposted: false,
    isBookmarked: false,
    type: "quote",
    originalPost: {
      _id: "post7",
      author: mockUsers[1],
      content: { text: "Vice City vibes are unmatched! Here's a collection of my favorite screenshots from the trailer. Which one is your favorite? 📸✨" },
      media: [
        {
          type: "image",
          url: "/images/HeaderImages/LuciaPool.jpg",
          thumbnail: "/images/HeaderImages/LuciaPool.jpg",
        },
        {
          type: "image",
          url: "/images/HeaderImages/Bros.jpg",
          thumbnail: "/images/HeaderImages/Bros.jpg",
        },
        {
          type: "image",
          url: "/images/HeaderImages/Stripaz.jpg",
          thumbnail: "/images/HeaderImages/Stripaz.jpg",
        },
      ],
      engagement: {
        likes: 892,
        reposts: 156,
        comments: 78,
        bookmarks: 234,
        views: 5600,
        quotes: 12,
      },
      createdAt: new Date(Date.now() - 7 * 60 * 60 * 1000),
    },
    createdAt: new Date(Date.now() - 17 * 60 * 60 * 1000), // 17 hours ago
    isEdited: false,
    isEditable: true,
  },
  // Text post with edited indicator
  {
    _id: "post18",
    author: mockUsers[3],
    content: { text: "Update: Just confirmed that the map will be even larger than initially reported! This is going to be epic! 🗺️🚀" },
    media: [],
    engagement: {
      likes: 5678,
      reposts: 1234,
      comments: 567,
      bookmarks: 1890,
      views: 23400,
      quotes: 123,
    },
    likes: 5678,
    reposts: 1234,
    comments: 567,
    bookmarks: 1890,
    views: 23400,
    isLiked: true,
    isReposted: true,
    isBookmarked: true,
    type: "post",
    createdAt: new Date(Date.now() - 18 * 60 * 60 * 1000), // 18 hours ago
    isEdited: true,
    isEditable: true,
  },
  // Repost of video
  {
    _id: "post19",
    author: mockUsers[4],
    content: { text: "" },
    media: [],
    engagement: {
      likes: 0,
      reposts: 0,
      comments: 0,
      bookmarks: 0,
      views: 0,
      quotes: 0,
    },
    likes: 0,
    reposts: 0,
    comments: 0,
    bookmarks: 0,
    views: 0,
    isLiked: false,
    isReposted: true,
    isBookmarked: false,
    type: "repost",
    originalPost: {
      _id: "post16",
      author: mockUsers[1],
      content: { text: "The character animations are so smooth! This is going to be the most immersive GTA experience yet! 🎬" },
      media: [
        {
          type: "video",
          url: "/src/assets/mockuser_videos/GTA6trailer1_Edited.mp4",
          thumbnail: "/images/HeaderImages/LuciaPool.jpg",
          metadata: {
            duration: 30,
            dimensions: { width: 1920, height: 1080 },
          },
        },
      ],
      engagement: {
        likes: 2345,
        reposts: 567,
        comments: 234,
        bookmarks: 678,
        views: 11200,
        quotes: 45,
      },
      createdAt: new Date(Date.now() - 16 * 60 * 60 * 1000),
    },
    createdAt: new Date(Date.now() - 19 * 60 * 60 * 1000), // 19 hours ago
    isEdited: false,
    isEditable: true,
  },
  // Multi-image post (3 images) with high engagement
  {
    _id: "post20",
    author: mockUsers[0],
    content: { text: "Character reveal breakdown! Each character brings something unique to the story. Which one are you most excited about? 🎭" },
    media: [
      {
        type: "image",
        url: "/images/HeaderImages/BikerGang.jpg",
        thumbnail: "/images/HeaderImages/BikerGang.jpg",
      },
      {
        type: "image",
        url: "/images/HeaderImages/draco.jpg",
        thumbnail: "/images/HeaderImages/draco.jpg",
      },
      {
        type: "image",
        url: "/images/HeaderImages/Stripaz.jpg",
        thumbnail: "/images/HeaderImages/Stripaz.jpg",
      },
    ],
    engagement: {
      likes: 4567,
      reposts: 1234,
      comments: 678,
      bookmarks: 2345,
      views: 18900,
      quotes: 156,
    },
    likes: 4567,
    reposts: 1234,
    comments: 678,
    bookmarks: 2345,
    views: 18900,
    isLiked: true,
    isReposted: false,
    isBookmarked: true,
    type: "post",
    createdAt: new Date(Date.now() - 20 * 60 * 60 * 1000), // 20 hours ago
    isEdited: false,
    isEditable: true,
  },
];

