// src/main.js
import { createApp } from "vue";
import store from "./store";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faSun,
  faMoon,
  faRightToBracket,
  faUserPlus,
  faTimes,
  faArrowLeft,
  faArrowRight,
  faPerson,
  faGun,
  faLocationPin,
  faBook,
  faCalendarDay,
  faUserGroup,
  faCity,
  faHouseChimney,
  faNewspaper,
  faCircleInfo,
  faPlay,
  faPause,
  faUser,
  faLocationDot,
  faLink,
  faCalendar,
  faGamepad,
  faUserCheck,
  faEnvelope,
  faEdit,
  faCog,
  faUsers,
  faTrophy,
  faChartBar,
  faHeart,
  faComment,
  faStar,
  faExclamationTriangle,
  faCamera,
  faTrash,
  faImage,
  faEllipsisH,
  faCheck,
  faCheckCircle,
  faFlag,
  faBan,
  faEyeSlash,
  faRetweet,
  faEye,
  faGlobe,
  faFire,
  faChartLine,
  faChevronLeft,
  faChevronRight,
  faBookmark,
  faReply,
  faBell,
  faCheckDouble,
  faTasks,
  faBookOpen,
  faBars,
  faSquarePlus,
  faSquare,
  faPlusCircle,
  faClock,
  faMap,
  faCodeBranch,
  faBug,
  faLightbulb,
  faRocket,
  faMugHot,
  faExternalLinkAlt,
  faCode,
  faServer,
  faPalette,
  faDatabase,
  faCircleNotch,
  faExclamationCircle,
} from "@fortawesome/free-solid-svg-icons";
import {
  faHeart as farHeart,
  faComment as farComment,
  faBookmark as farBookmark,
} from "@fortawesome/free-regular-svg-icons";
import {
  faGithub,
  faDiscord,
  faTwitter,
  faYoutube,
  faInstagram,
  faReddit,
  faVuejs,
  faJs,
  faCss3Alt,
  faHtml5,
} from "@fortawesome/free-brands-svg-icons";
import App from "./App.vue";
import router from "./router";
import "./assets/main.css";

library.add(
  faSun,
  faMoon,
  faRightToBracket,
  faUserPlus,
  faTimes,
  faArrowLeft,
  faArrowRight,
  faPerson,
  faGun,
  faLocationPin,
  faBook,
  faCalendarDay,
  faUserGroup,
  faCity,
  faHouseChimney,
  faNewspaper,
  faCircleInfo,
  faPlay,
  faPause,
  faUser,
  faLocationDot,
  faLink,
  faCalendar,
  faGamepad,
  faUserCheck,
  faEnvelope,
  faEdit,
  faCog,
  faUsers,
  faTrophy,
  faChartBar,
  faHeart,
  faComment,
  faStar,
  faExclamationTriangle,
  faCamera,
  faTrash,
  faImage,
  faEllipsisH,
  faCheck,
  faCheckCircle,
  faFlag,
  faBan,
  faEyeSlash,
  faRetweet,
  faEye,
  faGlobe,
  faFire,
  faChartLine,
  faChevronLeft,
  faChevronRight,
  faBookmark,
  faReply,
  faBell,
  faCheckDouble,
  faTasks,
  faBookOpen,
  faBars,
  faSquarePlus,
  faSquare,
  faPlusCircle,
  faClock,
  faMap,
  faCodeBranch,
  faBug,
  faLightbulb,
  faRocket,
  faMugHot,
  faExternalLinkAlt,
  faCode,
  faServer,
  faPalette,
  faDatabase,
  faCircleNotch,
  faExclamationCircle,
  farHeart,
  farComment,
  farBookmark,
  // Brand icons
  faGithub,
  faDiscord,
  faTwitter,
  faYoutube,
  faInstagram,
  faReddit,
  faVuejs,
  faJs,
  faCss3Alt,
  faHtml5
);

window.scrollBy({
  top: -1100, // could be negative value
  left: 0,
  behavior: "smooth",
});

// Register Service Worker
if ("serviceWorker" in navigator) {
  window.addEventListener("load", () => {
    navigator.serviceWorker
      .register("/sw.js")
      .then((registration) => {
        console.log("Service Worker registered:", registration);
      })
      .catch((error) => {
        console.error("Service Worker registration failed:", error);
      });
  });
}
const app = createApp(App);
app.use(router);
app.use(store);
app.component("font-awesome-icon", FontAwesomeIcon);
app.mount("#app");
